import * as Lucide from "lucide-react";

const ICONS = {
  activity: Lucide.Activity,
  alertCircle: Lucide.CircleAlert,
  alertTriangle: Lucide.TriangleAlert,
  arrowsMaximize: Lucide.Maximize,
  ban: Lucide.Ban,
  bell: Lucide.Bell,
  book: Lucide.BookOpen,
  chart: Lucide.ChartColumn,
  check: Lucide.Check,
  chevronDown: Lucide.ChevronDown,
  chevronUp: Lucide.ChevronUp,
  circleCheck: Lucide.CircleCheck,
  circleCheckFilled: Lucide.CircleCheck,
  circleOff: Lucide.CircleOff,
  copy: Lucide.Copy,
  docs: Lucide.FileText,
  download: Lucide.Download,
  fileText: Lucide.FileText,
  filter: Lucide.Filter,
  folder: Lucide.Folder,
  folderUp: Lucide.FolderUp,
  history: Lucide.History,
  home: Lucide.Home,
  info: Lucide.Info,
  lock: Lucide.Lock,
  lockCheck: Lucide.LockKeyhole,
  matrix: Lucide.Network,
  menu: Lucide.Menu,
  minus: Lucide.Minus,
  pencil: Lucide.Pencil,
  play: Lucide.Play,
  plus: Lucide.Plus,
  ports: Lucide.Server,
  provisioning: Lucide.ShieldCog,
  refresh: Lucide.RefreshCw,
  rollbackPreview: Lucide.RotateCcw,
  save: Lucide.Save,
  search: Lucide.Search,
  shieldCheck: Lucide.ShieldCheck,
  switch: Lucide.Shuffle,
  telemetry: Lucide.ChartNoAxesColumn,
  tool: Lucide.Wrench,
  trash: Lucide.Trash2,
  upload: Lucide.Upload,
  userCircle: Lucide.CircleUserRound,
  userCog: Lucide.UserCog,
  x: Lucide.X,
};

export function Icon({ name, className = "", size = 18, strokeWidth = 2 }) {
  const Component = ICONS[name] || Lucide.Square;
  return <Component aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} />;
}
